name: Cron Job

on:
  schedule:
    - cron: '*/5 * * * *'  # 5분마다 실행
  workflow_dispatch:  # 수동 실행 가능

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call News Collection API
        run: |
          curl -X GET ${{ secrets.VERCEL_URL }}/api/cron/collect-news \
          -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" 