name: Cron Job

on:
  schedule:
    - cron: '*/5 * * * *'  # 5분마다 실행
  workflow_dispatch:  # 수동 실행 가능

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call News Collection API
        run: |
          # API URL 출력 (시크릿 값은 마스킹됨)
          echo "API URL: ${{ secrets.VERCEL_URL }}/api/cron/collect-news"
          
          # curl 요청 실행 및 응답 저장
          response=$(curl -v -X POST "${{ secrets.VERCEL_URL }}/api/cron/collect-news" \
            -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" \
            -H "Content-Type: application/json" \
            -w "\nStatus Code: %{http_code}" \
            2>&1)
          
          # 전체 응답 출력 (디버깅용)
          echo "Full response:"
          echo "$response"
          
          # HTTP 상태 코드 추출
          status_code=$(echo "$response" | grep "Status Code:" | cut -d' ' -f3)
          
          echo "Status code: $status_code"
          
          # 상태 코드가 200이 아니면 실패
          if [ -z "$status_code" ] || [ "$status_code" != "200" ]; then
            echo "Error: API call failed with status code $status_code"
            exit 1
          fi
          
          echo "API call successful!" 